# Generated by Django 4.2.16 on 2024-11-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='crested_at',
            new_name='created_at',
        ),
    ]
